/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Mood = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'emoji' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllMoods' : IDL.Func([], [IDL.Vec(Mood)], ['query']),
  'getRandomMood' : IDL.Func([], [Mood], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Mood = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'emoji' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllMoods' : IDL.Func([], [IDL.Vec(Mood)], ['query']),
    'getRandomMood' : IDL.Func([], [Mood], []),
  });
};

export const init = ({ IDL }) => { return []; };